/* eslint-disable */
import * as types from './graphql';



/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "query MostFavoritedCharacters($page: Int, $perPage: Int) {\n  Page(page: $page, perPage: $perPage) {\n    characters(sort: FAVOURITES_DESC) {\n      ...CharacterCard\n    }\n    ...PageInfoData\n  }\n}\n\nquery BirthdayCharacters($page: Int, $perPage: Int) {\n  Page(page: $page, perPage: $perPage) {\n    characters(isBirthday: true, sort: FAVOURITES_DESC) {\n      ...CharacterCard\n    }\n    ...PageInfoData\n  }\n}\n\nquery CharacterAll($page: Int, $perPage: Int) {\n  birthday: Page(page: $page, perPage: $perPage) {\n    characters(isBirthday: true, sort: FAVOURITES_DESC) {\n      ...CharacterCard\n    }\n    ...PageInfoData\n  }\n  mostFavorited: Page(page: $page, perPage: $perPage) {\n    characters(sort: FAVOURITES_DESC) {\n      ...CharacterCard\n    }\n    ...PageInfoData\n  }\n}\n\nquery CharacterDetailQuery($characterId: Int, $mediaSort: [MediaSort], $voiceActorsLanguage: StaffLanguage, $voiceActorsSort: [StaffSort]) {\n  Character(id: $characterId) {\n    ...CharacterDetail\n  }\n}": typeof types.MostFavoritedCharactersDocument,
    "fragment CharacterCard on Character {\n  id\n  description(asHtml: true)\n  gender\n  age\n  name {\n    full\n    native\n  }\n  image {\n    large\n    medium\n  }\n}\n\nfragment CharacterDetail on Character {\n  id\n  description(asHtml: true)\n  gender\n  age\n  favourites\n  bloodType\n  siteUrl\n  name {\n    full\n    native\n    alternative\n    alternativeSpoiler\n  }\n  image {\n    large\n    medium\n  }\n  dateOfBirth {\n    day\n    month\n    year\n  }\n  media(sort: $mediaSort) {\n    edges {\n      id\n      node {\n        id\n        type\n        coverImage {\n          extraLarge\n          large\n          medium\n        }\n        title {\n          english\n          native\n          romaji\n        }\n      }\n      voiceActors(language: $voiceActorsLanguage, sort: $voiceActorsSort) {\n        id\n        name {\n          full\n          native\n        }\n        image {\n          large\n          medium\n        }\n      }\n    }\n  }\n}": typeof types.CharacterCardFragmentDoc,
    "query TrendingAnime($page: Int, $perPage: Int) {\n  Page(page: $page, perPage: $perPage) {\n    media(sort: TRENDING_DESC, type: ANIME) {\n      ...MediaCard\n    }\n    ...PageInfoData\n  }\n}\n\nquery PopularAnime($page: Int, $perPage: Int) {\n  Page(page: $page, perPage: $perPage) {\n    media(sort: POPULARITY_DESC, type: ANIME) {\n      ...MediaCard\n    }\n    ...PageInfoData\n  }\n}\n\nquery PopularThisSeasonAnime($page: Int, $perPage: Int, $season: MediaSeason, $seasonYear: Int) {\n  Page(page: $page, perPage: $perPage) {\n    media(\n      sort: POPULARITY_DESC\n      type: ANIME\n      season: $season\n      seasonYear: $seasonYear\n    ) {\n      ...MediaCard\n    }\n    ...PageInfoData\n  }\n}\n\nquery UpcomingAnime($page: Int, $perPage: Int, $season: MediaSeason, $seasonYear: Int) {\n  Page(page: $page, perPage: $perPage) {\n    media(\n      sort: POPULARITY_DESC\n      type: ANIME\n      season: $season\n      seasonYear: $seasonYear\n    ) {\n      ...MediaCard\n    }\n    ...PageInfoData\n  }\n}\n\nquery TrendingAnimeBanner($page: Int, $perPage: Int) {\n  Page(page: $page, perPage: $perPage) {\n    media(sort: TRENDING_DESC, type: ANIME) {\n      ...MediaBanner\n    }\n    ...PageInfoData\n  }\n}\n\nquery AnimeAll($page: Int, $perPage: Int, $popularThisSeasonSeason: MediaSeason, $popularThisSeasonSeasonYear: Int, $upcomingSeason: MediaSeason, $upcomingSeasonYear: Int) {\n  trendingAnimeBanner: Page(page: $page, perPage: $perPage) {\n    media(sort: TRENDING_DESC, type: ANIME) {\n      ...MediaBanner\n    }\n    ...PageInfoData\n  }\n  trending: Page(page: $page, perPage: $perPage) {\n    media(sort: TRENDING_DESC, type: ANIME) {\n      ...MediaCard\n    }\n    ...PageInfoData\n  }\n  popular: Page(page: $page, perPage: $perPage) {\n    media(sort: POPULARITY_DESC, type: ANIME) {\n      ...MediaCard\n    }\n    ...PageInfoData\n  }\n  popularThisSeason: Page(page: $page, perPage: $perPage) {\n    media(\n      sort: POPULARITY_DESC\n      type: ANIME\n      season: $popularThisSeasonSeason\n      seasonYear: $popularThisSeasonSeasonYear\n    ) {\n      ...MediaCard\n    }\n    ...PageInfoData\n  }\n  upcoming: Page(page: $page, perPage: $perPage) {\n    media(\n      sort: POPULARITY_DESC\n      type: ANIME\n      season: $upcomingSeason\n      seasonYear: $upcomingSeasonYear\n    ) {\n      ...MediaCard\n    }\n    ...PageInfoData\n  }\n}": typeof types.TrendingAnimeDocument,
    "query TrendingManga($page: Int, $perPage: Int) {\n  Page(page: $page, perPage: $perPage) {\n    media(sort: TRENDING_DESC, type: MANGA) {\n      ...MediaCard\n    }\n    ...PageInfoData\n  }\n}\n\nquery PopularManga($page: Int, $perPage: Int) {\n  Page(page: $page, perPage: $perPage) {\n    media(sort: POPULARITY_DESC, type: MANGA) {\n      ...MediaCard\n    }\n    ...PageInfoData\n  }\n}\n\nquery PopularManhwa($page: Int, $perPage: Int) {\n  Page(page: $page, perPage: $perPage) {\n    media(sort: POPULARITY_DESC, type: MANGA, countryOfOrigin: \"KR\") {\n      ...MediaCard\n    }\n    ...PageInfoData\n  }\n}\n\nquery TrendingMangaBanner($page: Int, $perPage: Int) {\n  Page(page: $page, perPage: $perPage) {\n    media(sort: TRENDING_DESC, type: MANGA) {\n      ...MediaBanner\n    }\n    ...PageInfoData\n  }\n}\n\nquery MangaAll($page: Int, $perPage: Int) {\n  trendingMangaBanner: Page(page: $page, perPage: $perPage) {\n    media(sort: TRENDING_DESC, type: MANGA) {\n      ...MediaBanner\n    }\n    ...PageInfoData\n  }\n  trending: Page(page: $page, perPage: $perPage) {\n    media(sort: TRENDING_DESC, type: MANGA) {\n      ...MediaCard\n    }\n    ...PageInfoData\n  }\n  popular: Page(page: $page, perPage: $perPage) {\n    media(sort: POPULARITY_DESC, type: MANGA) {\n      ...MediaCard\n    }\n    ...PageInfoData\n  }\n  popularManhwa: Page(page: $page, perPage: $perPage) {\n    media(sort: POPULARITY_DESC, countryOfOrigin: KR, type: MANGA) {\n      ...MediaCard\n    }\n    ...PageInfoData\n  }\n}": typeof types.TrendingMangaDocument,
    "fragment MediaCard on Media {\n  title {\n    romaji\n    english\n    native\n  }\n  coverImage {\n    extraLarge\n    large\n    medium\n  }\n  averageScore\n  description(asHtml: true)\n  status\n  id\n  genres\n  format\n  type\n}\n\nfragment MediaBanner on Media {\n  title {\n    romaji\n    english\n    native\n  }\n  bannerImage\n  id\n  genres\n  type\n}\n\nfragment MediaDetail on Media {\n  id\n  type\n  synonyms\n  title {\n    english\n    romaji\n    native\n  }\n  chapters\n  volumes\n  episodes\n  duration\n  averageScore\n  countryOfOrigin\n  bannerImage\n  hashtag\n  coverImage {\n    extraLarge\n    large\n    medium\n  }\n  description(asHtml: true)\n  externalLinks {\n    icon\n    id\n    type\n    url\n    site\n    language\n    siteId\n  }\n  format\n  genres\n  nextAiringEpisode {\n    airingAt\n    episode\n    id\n    timeUntilAiring\n  }\n  rankings {\n    allTime\n    context\n    rank\n    type\n    format\n    id\n    season\n    year\n  }\n  endDate {\n    year\n    month\n    day\n  }\n  updatedAt\n  seasonYear\n  season\n  startDate {\n    year\n    month\n    day\n  }\n  source\n  siteUrl\n  status\n  streamingEpisodes {\n    title\n    thumbnail\n    url\n    site\n  }\n  studios {\n    nodes {\n      id\n      name\n      siteUrl\n    }\n  }\n  trailer {\n    id\n    site\n    thumbnail\n  }\n  characters {\n    edges {\n      id\n      node {\n        id\n        image {\n          large\n          medium\n        }\n        name {\n          full\n          native\n        }\n      }\n      voiceActors(language: $voiceActorLanguage) {\n        id\n        image {\n          large\n          medium\n        }\n        name {\n          full\n          native\n        }\n      }\n    }\n  }\n  recommendations(sort: $recommendationSort) {\n    nodes {\n      id\n      mediaRecommendation {\n        id\n        title {\n          english\n          native\n          romaji\n        }\n        coverImage {\n          extraLarge\n          large\n          medium\n        }\n      }\n    }\n  }\n  relations {\n    edges {\n      id\n      relationType\n      node {\n        format\n        type\n        id\n        title {\n          english\n          native\n          romaji\n        }\n        coverImage {\n          extraLarge\n          large\n          medium\n        }\n      }\n    }\n  }\n  staff(sort: $staffSort) {\n    nodes {\n      id\n      image {\n        large\n        medium\n      }\n      name {\n        full\n        native\n      }\n    }\n  }\n}": typeof types.MediaCardFragmentDoc,
    "query MediaDetailQuery($mediaId: Int, $voiceActorLanguage: StaffLanguage, $recommendationSort: [RecommendationSort], $staffSort: [StaffSort]) {\n  Media(id: $mediaId) {\n    ...MediaDetail\n  }\n}": typeof types.MediaDetailQueryDocument,
    "fragment PageInfoData on Page {\n  pageInfo {\n    total\n    perPage\n    currentPage\n    lastPage\n    hasNextPage\n  }\n}": typeof types.PageInfoDataFragmentDoc,
    "fragment StaffCard on Staff {\n  age\n  description(asHtml: true)\n  gender\n  id\n  primaryOccupations\n  image {\n    large\n    medium\n  }\n  name {\n    full\n    native\n  }\n}\n\nfragment StaffDetail on Staff {\n  age\n  id\n  description(asHtml: true)\n  homeTown\n  siteUrl\n  yearsActive\n  gender\n  primaryOccupations\n  name {\n    full\n    native\n    alternative\n  }\n  image {\n    large\n    medium\n  }\n  dateOfBirth {\n    day\n    month\n    year\n  }\n  dateOfDeath {\n    day\n    month\n    year\n  }\n  characterMedia(sort: $characterMediaSort) {\n    edges {\n      id\n      node {\n        id\n        type\n        coverImage {\n          extraLarge\n          large\n          medium\n        }\n        title {\n          english\n          native\n          romaji\n        }\n      }\n      characters {\n        id\n        name {\n          full\n          native\n        }\n        image {\n          large\n          medium\n        }\n      }\n    }\n  }\n}": typeof types.StaffCardFragmentDoc,
};
const documents: Documents = {
    "query MostFavoritedCharacters($page: Int, $perPage: Int) {\n  Page(page: $page, perPage: $perPage) {\n    characters(sort: FAVOURITES_DESC) {\n      ...CharacterCard\n    }\n    ...PageInfoData\n  }\n}\n\nquery BirthdayCharacters($page: Int, $perPage: Int) {\n  Page(page: $page, perPage: $perPage) {\n    characters(isBirthday: true, sort: FAVOURITES_DESC) {\n      ...CharacterCard\n    }\n    ...PageInfoData\n  }\n}\n\nquery CharacterAll($page: Int, $perPage: Int) {\n  birthday: Page(page: $page, perPage: $perPage) {\n    characters(isBirthday: true, sort: FAVOURITES_DESC) {\n      ...CharacterCard\n    }\n    ...PageInfoData\n  }\n  mostFavorited: Page(page: $page, perPage: $perPage) {\n    characters(sort: FAVOURITES_DESC) {\n      ...CharacterCard\n    }\n    ...PageInfoData\n  }\n}\n\nquery CharacterDetailQuery($characterId: Int, $mediaSort: [MediaSort], $voiceActorsLanguage: StaffLanguage, $voiceActorsSort: [StaffSort]) {\n  Character(id: $characterId) {\n    ...CharacterDetail\n  }\n}": types.MostFavoritedCharactersDocument,
    "fragment CharacterCard on Character {\n  id\n  description(asHtml: true)\n  gender\n  age\n  name {\n    full\n    native\n  }\n  image {\n    large\n    medium\n  }\n}\n\nfragment CharacterDetail on Character {\n  id\n  description(asHtml: true)\n  gender\n  age\n  favourites\n  bloodType\n  siteUrl\n  name {\n    full\n    native\n    alternative\n    alternativeSpoiler\n  }\n  image {\n    large\n    medium\n  }\n  dateOfBirth {\n    day\n    month\n    year\n  }\n  media(sort: $mediaSort) {\n    edges {\n      id\n      node {\n        id\n        type\n        coverImage {\n          extraLarge\n          large\n          medium\n        }\n        title {\n          english\n          native\n          romaji\n        }\n      }\n      voiceActors(language: $voiceActorsLanguage, sort: $voiceActorsSort) {\n        id\n        name {\n          full\n          native\n        }\n        image {\n          large\n          medium\n        }\n      }\n    }\n  }\n}": types.CharacterCardFragmentDoc,
    "query TrendingAnime($page: Int, $perPage: Int) {\n  Page(page: $page, perPage: $perPage) {\n    media(sort: TRENDING_DESC, type: ANIME) {\n      ...MediaCard\n    }\n    ...PageInfoData\n  }\n}\n\nquery PopularAnime($page: Int, $perPage: Int) {\n  Page(page: $page, perPage: $perPage) {\n    media(sort: POPULARITY_DESC, type: ANIME) {\n      ...MediaCard\n    }\n    ...PageInfoData\n  }\n}\n\nquery PopularThisSeasonAnime($page: Int, $perPage: Int, $season: MediaSeason, $seasonYear: Int) {\n  Page(page: $page, perPage: $perPage) {\n    media(\n      sort: POPULARITY_DESC\n      type: ANIME\n      season: $season\n      seasonYear: $seasonYear\n    ) {\n      ...MediaCard\n    }\n    ...PageInfoData\n  }\n}\n\nquery UpcomingAnime($page: Int, $perPage: Int, $season: MediaSeason, $seasonYear: Int) {\n  Page(page: $page, perPage: $perPage) {\n    media(\n      sort: POPULARITY_DESC\n      type: ANIME\n      season: $season\n      seasonYear: $seasonYear\n    ) {\n      ...MediaCard\n    }\n    ...PageInfoData\n  }\n}\n\nquery TrendingAnimeBanner($page: Int, $perPage: Int) {\n  Page(page: $page, perPage: $perPage) {\n    media(sort: TRENDING_DESC, type: ANIME) {\n      ...MediaBanner\n    }\n    ...PageInfoData\n  }\n}\n\nquery AnimeAll($page: Int, $perPage: Int, $popularThisSeasonSeason: MediaSeason, $popularThisSeasonSeasonYear: Int, $upcomingSeason: MediaSeason, $upcomingSeasonYear: Int) {\n  trendingAnimeBanner: Page(page: $page, perPage: $perPage) {\n    media(sort: TRENDING_DESC, type: ANIME) {\n      ...MediaBanner\n    }\n    ...PageInfoData\n  }\n  trending: Page(page: $page, perPage: $perPage) {\n    media(sort: TRENDING_DESC, type: ANIME) {\n      ...MediaCard\n    }\n    ...PageInfoData\n  }\n  popular: Page(page: $page, perPage: $perPage) {\n    media(sort: POPULARITY_DESC, type: ANIME) {\n      ...MediaCard\n    }\n    ...PageInfoData\n  }\n  popularThisSeason: Page(page: $page, perPage: $perPage) {\n    media(\n      sort: POPULARITY_DESC\n      type: ANIME\n      season: $popularThisSeasonSeason\n      seasonYear: $popularThisSeasonSeasonYear\n    ) {\n      ...MediaCard\n    }\n    ...PageInfoData\n  }\n  upcoming: Page(page: $page, perPage: $perPage) {\n    media(\n      sort: POPULARITY_DESC\n      type: ANIME\n      season: $upcomingSeason\n      seasonYear: $upcomingSeasonYear\n    ) {\n      ...MediaCard\n    }\n    ...PageInfoData\n  }\n}": types.TrendingAnimeDocument,
    "query TrendingManga($page: Int, $perPage: Int) {\n  Page(page: $page, perPage: $perPage) {\n    media(sort: TRENDING_DESC, type: MANGA) {\n      ...MediaCard\n    }\n    ...PageInfoData\n  }\n}\n\nquery PopularManga($page: Int, $perPage: Int) {\n  Page(page: $page, perPage: $perPage) {\n    media(sort: POPULARITY_DESC, type: MANGA) {\n      ...MediaCard\n    }\n    ...PageInfoData\n  }\n}\n\nquery PopularManhwa($page: Int, $perPage: Int) {\n  Page(page: $page, perPage: $perPage) {\n    media(sort: POPULARITY_DESC, type: MANGA, countryOfOrigin: \"KR\") {\n      ...MediaCard\n    }\n    ...PageInfoData\n  }\n}\n\nquery TrendingMangaBanner($page: Int, $perPage: Int) {\n  Page(page: $page, perPage: $perPage) {\n    media(sort: TRENDING_DESC, type: MANGA) {\n      ...MediaBanner\n    }\n    ...PageInfoData\n  }\n}\n\nquery MangaAll($page: Int, $perPage: Int) {\n  trendingMangaBanner: Page(page: $page, perPage: $perPage) {\n    media(sort: TRENDING_DESC, type: MANGA) {\n      ...MediaBanner\n    }\n    ...PageInfoData\n  }\n  trending: Page(page: $page, perPage: $perPage) {\n    media(sort: TRENDING_DESC, type: MANGA) {\n      ...MediaCard\n    }\n    ...PageInfoData\n  }\n  popular: Page(page: $page, perPage: $perPage) {\n    media(sort: POPULARITY_DESC, type: MANGA) {\n      ...MediaCard\n    }\n    ...PageInfoData\n  }\n  popularManhwa: Page(page: $page, perPage: $perPage) {\n    media(sort: POPULARITY_DESC, countryOfOrigin: KR, type: MANGA) {\n      ...MediaCard\n    }\n    ...PageInfoData\n  }\n}": types.TrendingMangaDocument,
    "fragment MediaCard on Media {\n  title {\n    romaji\n    english\n    native\n  }\n  coverImage {\n    extraLarge\n    large\n    medium\n  }\n  averageScore\n  description(asHtml: true)\n  status\n  id\n  genres\n  format\n  type\n}\n\nfragment MediaBanner on Media {\n  title {\n    romaji\n    english\n    native\n  }\n  bannerImage\n  id\n  genres\n  type\n}\n\nfragment MediaDetail on Media {\n  id\n  type\n  synonyms\n  title {\n    english\n    romaji\n    native\n  }\n  chapters\n  volumes\n  episodes\n  duration\n  averageScore\n  countryOfOrigin\n  bannerImage\n  hashtag\n  coverImage {\n    extraLarge\n    large\n    medium\n  }\n  description(asHtml: true)\n  externalLinks {\n    icon\n    id\n    type\n    url\n    site\n    language\n    siteId\n  }\n  format\n  genres\n  nextAiringEpisode {\n    airingAt\n    episode\n    id\n    timeUntilAiring\n  }\n  rankings {\n    allTime\n    context\n    rank\n    type\n    format\n    id\n    season\n    year\n  }\n  endDate {\n    year\n    month\n    day\n  }\n  updatedAt\n  seasonYear\n  season\n  startDate {\n    year\n    month\n    day\n  }\n  source\n  siteUrl\n  status\n  streamingEpisodes {\n    title\n    thumbnail\n    url\n    site\n  }\n  studios {\n    nodes {\n      id\n      name\n      siteUrl\n    }\n  }\n  trailer {\n    id\n    site\n    thumbnail\n  }\n  characters {\n    edges {\n      id\n      node {\n        id\n        image {\n          large\n          medium\n        }\n        name {\n          full\n          native\n        }\n      }\n      voiceActors(language: $voiceActorLanguage) {\n        id\n        image {\n          large\n          medium\n        }\n        name {\n          full\n          native\n        }\n      }\n    }\n  }\n  recommendations(sort: $recommendationSort) {\n    nodes {\n      id\n      mediaRecommendation {\n        id\n        title {\n          english\n          native\n          romaji\n        }\n        coverImage {\n          extraLarge\n          large\n          medium\n        }\n      }\n    }\n  }\n  relations {\n    edges {\n      id\n      relationType\n      node {\n        format\n        type\n        id\n        title {\n          english\n          native\n          romaji\n        }\n        coverImage {\n          extraLarge\n          large\n          medium\n        }\n      }\n    }\n  }\n  staff(sort: $staffSort) {\n    nodes {\n      id\n      image {\n        large\n        medium\n      }\n      name {\n        full\n        native\n      }\n    }\n  }\n}": types.MediaCardFragmentDoc,
    "query MediaDetailQuery($mediaId: Int, $voiceActorLanguage: StaffLanguage, $recommendationSort: [RecommendationSort], $staffSort: [StaffSort]) {\n  Media(id: $mediaId) {\n    ...MediaDetail\n  }\n}": types.MediaDetailQueryDocument,
    "fragment PageInfoData on Page {\n  pageInfo {\n    total\n    perPage\n    currentPage\n    lastPage\n    hasNextPage\n  }\n}": types.PageInfoDataFragmentDoc,
    "fragment StaffCard on Staff {\n  age\n  description(asHtml: true)\n  gender\n  id\n  primaryOccupations\n  image {\n    large\n    medium\n  }\n  name {\n    full\n    native\n  }\n}\n\nfragment StaffDetail on Staff {\n  age\n  id\n  description(asHtml: true)\n  homeTown\n  siteUrl\n  yearsActive\n  gender\n  primaryOccupations\n  name {\n    full\n    native\n    alternative\n  }\n  image {\n    large\n    medium\n  }\n  dateOfBirth {\n    day\n    month\n    year\n  }\n  dateOfDeath {\n    day\n    month\n    year\n  }\n  characterMedia(sort: $characterMediaSort) {\n    edges {\n      id\n      node {\n        id\n        type\n        coverImage {\n          extraLarge\n          large\n          medium\n        }\n        title {\n          english\n          native\n          romaji\n        }\n      }\n      characters {\n        id\n        name {\n          full\n          native\n        }\n        image {\n          large\n          medium\n        }\n      }\n    }\n  }\n}": types.StaffCardFragmentDoc,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query MostFavoritedCharacters($page: Int, $perPage: Int) {\n  Page(page: $page, perPage: $perPage) {\n    characters(sort: FAVOURITES_DESC) {\n      ...CharacterCard\n    }\n    ...PageInfoData\n  }\n}\n\nquery BirthdayCharacters($page: Int, $perPage: Int) {\n  Page(page: $page, perPage: $perPage) {\n    characters(isBirthday: true, sort: FAVOURITES_DESC) {\n      ...CharacterCard\n    }\n    ...PageInfoData\n  }\n}\n\nquery CharacterAll($page: Int, $perPage: Int) {\n  birthday: Page(page: $page, perPage: $perPage) {\n    characters(isBirthday: true, sort: FAVOURITES_DESC) {\n      ...CharacterCard\n    }\n    ...PageInfoData\n  }\n  mostFavorited: Page(page: $page, perPage: $perPage) {\n    characters(sort: FAVOURITES_DESC) {\n      ...CharacterCard\n    }\n    ...PageInfoData\n  }\n}\n\nquery CharacterDetailQuery($characterId: Int, $mediaSort: [MediaSort], $voiceActorsLanguage: StaffLanguage, $voiceActorsSort: [StaffSort]) {\n  Character(id: $characterId) {\n    ...CharacterDetail\n  }\n}"): typeof import('./graphql').MostFavoritedCharactersDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "fragment CharacterCard on Character {\n  id\n  description(asHtml: true)\n  gender\n  age\n  name {\n    full\n    native\n  }\n  image {\n    large\n    medium\n  }\n}\n\nfragment CharacterDetail on Character {\n  id\n  description(asHtml: true)\n  gender\n  age\n  favourites\n  bloodType\n  siteUrl\n  name {\n    full\n    native\n    alternative\n    alternativeSpoiler\n  }\n  image {\n    large\n    medium\n  }\n  dateOfBirth {\n    day\n    month\n    year\n  }\n  media(sort: $mediaSort) {\n    edges {\n      id\n      node {\n        id\n        type\n        coverImage {\n          extraLarge\n          large\n          medium\n        }\n        title {\n          english\n          native\n          romaji\n        }\n      }\n      voiceActors(language: $voiceActorsLanguage, sort: $voiceActorsSort) {\n        id\n        name {\n          full\n          native\n        }\n        image {\n          large\n          medium\n        }\n      }\n    }\n  }\n}"): typeof import('./graphql').CharacterCardFragmentDoc;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query TrendingAnime($page: Int, $perPage: Int) {\n  Page(page: $page, perPage: $perPage) {\n    media(sort: TRENDING_DESC, type: ANIME) {\n      ...MediaCard\n    }\n    ...PageInfoData\n  }\n}\n\nquery PopularAnime($page: Int, $perPage: Int) {\n  Page(page: $page, perPage: $perPage) {\n    media(sort: POPULARITY_DESC, type: ANIME) {\n      ...MediaCard\n    }\n    ...PageInfoData\n  }\n}\n\nquery PopularThisSeasonAnime($page: Int, $perPage: Int, $season: MediaSeason, $seasonYear: Int) {\n  Page(page: $page, perPage: $perPage) {\n    media(\n      sort: POPULARITY_DESC\n      type: ANIME\n      season: $season\n      seasonYear: $seasonYear\n    ) {\n      ...MediaCard\n    }\n    ...PageInfoData\n  }\n}\n\nquery UpcomingAnime($page: Int, $perPage: Int, $season: MediaSeason, $seasonYear: Int) {\n  Page(page: $page, perPage: $perPage) {\n    media(\n      sort: POPULARITY_DESC\n      type: ANIME\n      season: $season\n      seasonYear: $seasonYear\n    ) {\n      ...MediaCard\n    }\n    ...PageInfoData\n  }\n}\n\nquery TrendingAnimeBanner($page: Int, $perPage: Int) {\n  Page(page: $page, perPage: $perPage) {\n    media(sort: TRENDING_DESC, type: ANIME) {\n      ...MediaBanner\n    }\n    ...PageInfoData\n  }\n}\n\nquery AnimeAll($page: Int, $perPage: Int, $popularThisSeasonSeason: MediaSeason, $popularThisSeasonSeasonYear: Int, $upcomingSeason: MediaSeason, $upcomingSeasonYear: Int) {\n  trendingAnimeBanner: Page(page: $page, perPage: $perPage) {\n    media(sort: TRENDING_DESC, type: ANIME) {\n      ...MediaBanner\n    }\n    ...PageInfoData\n  }\n  trending: Page(page: $page, perPage: $perPage) {\n    media(sort: TRENDING_DESC, type: ANIME) {\n      ...MediaCard\n    }\n    ...PageInfoData\n  }\n  popular: Page(page: $page, perPage: $perPage) {\n    media(sort: POPULARITY_DESC, type: ANIME) {\n      ...MediaCard\n    }\n    ...PageInfoData\n  }\n  popularThisSeason: Page(page: $page, perPage: $perPage) {\n    media(\n      sort: POPULARITY_DESC\n      type: ANIME\n      season: $popularThisSeasonSeason\n      seasonYear: $popularThisSeasonSeasonYear\n    ) {\n      ...MediaCard\n    }\n    ...PageInfoData\n  }\n  upcoming: Page(page: $page, perPage: $perPage) {\n    media(\n      sort: POPULARITY_DESC\n      type: ANIME\n      season: $upcomingSeason\n      seasonYear: $upcomingSeasonYear\n    ) {\n      ...MediaCard\n    }\n    ...PageInfoData\n  }\n}"): typeof import('./graphql').TrendingAnimeDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query TrendingManga($page: Int, $perPage: Int) {\n  Page(page: $page, perPage: $perPage) {\n    media(sort: TRENDING_DESC, type: MANGA) {\n      ...MediaCard\n    }\n    ...PageInfoData\n  }\n}\n\nquery PopularManga($page: Int, $perPage: Int) {\n  Page(page: $page, perPage: $perPage) {\n    media(sort: POPULARITY_DESC, type: MANGA) {\n      ...MediaCard\n    }\n    ...PageInfoData\n  }\n}\n\nquery PopularManhwa($page: Int, $perPage: Int) {\n  Page(page: $page, perPage: $perPage) {\n    media(sort: POPULARITY_DESC, type: MANGA, countryOfOrigin: \"KR\") {\n      ...MediaCard\n    }\n    ...PageInfoData\n  }\n}\n\nquery TrendingMangaBanner($page: Int, $perPage: Int) {\n  Page(page: $page, perPage: $perPage) {\n    media(sort: TRENDING_DESC, type: MANGA) {\n      ...MediaBanner\n    }\n    ...PageInfoData\n  }\n}\n\nquery MangaAll($page: Int, $perPage: Int) {\n  trendingMangaBanner: Page(page: $page, perPage: $perPage) {\n    media(sort: TRENDING_DESC, type: MANGA) {\n      ...MediaBanner\n    }\n    ...PageInfoData\n  }\n  trending: Page(page: $page, perPage: $perPage) {\n    media(sort: TRENDING_DESC, type: MANGA) {\n      ...MediaCard\n    }\n    ...PageInfoData\n  }\n  popular: Page(page: $page, perPage: $perPage) {\n    media(sort: POPULARITY_DESC, type: MANGA) {\n      ...MediaCard\n    }\n    ...PageInfoData\n  }\n  popularManhwa: Page(page: $page, perPage: $perPage) {\n    media(sort: POPULARITY_DESC, countryOfOrigin: KR, type: MANGA) {\n      ...MediaCard\n    }\n    ...PageInfoData\n  }\n}"): typeof import('./graphql').TrendingMangaDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "fragment MediaCard on Media {\n  title {\n    romaji\n    english\n    native\n  }\n  coverImage {\n    extraLarge\n    large\n    medium\n  }\n  averageScore\n  description(asHtml: true)\n  status\n  id\n  genres\n  format\n  type\n}\n\nfragment MediaBanner on Media {\n  title {\n    romaji\n    english\n    native\n  }\n  bannerImage\n  id\n  genres\n  type\n}\n\nfragment MediaDetail on Media {\n  id\n  type\n  synonyms\n  title {\n    english\n    romaji\n    native\n  }\n  chapters\n  volumes\n  episodes\n  duration\n  averageScore\n  countryOfOrigin\n  bannerImage\n  hashtag\n  coverImage {\n    extraLarge\n    large\n    medium\n  }\n  description(asHtml: true)\n  externalLinks {\n    icon\n    id\n    type\n    url\n    site\n    language\n    siteId\n  }\n  format\n  genres\n  nextAiringEpisode {\n    airingAt\n    episode\n    id\n    timeUntilAiring\n  }\n  rankings {\n    allTime\n    context\n    rank\n    type\n    format\n    id\n    season\n    year\n  }\n  endDate {\n    year\n    month\n    day\n  }\n  updatedAt\n  seasonYear\n  season\n  startDate {\n    year\n    month\n    day\n  }\n  source\n  siteUrl\n  status\n  streamingEpisodes {\n    title\n    thumbnail\n    url\n    site\n  }\n  studios {\n    nodes {\n      id\n      name\n      siteUrl\n    }\n  }\n  trailer {\n    id\n    site\n    thumbnail\n  }\n  characters {\n    edges {\n      id\n      node {\n        id\n        image {\n          large\n          medium\n        }\n        name {\n          full\n          native\n        }\n      }\n      voiceActors(language: $voiceActorLanguage) {\n        id\n        image {\n          large\n          medium\n        }\n        name {\n          full\n          native\n        }\n      }\n    }\n  }\n  recommendations(sort: $recommendationSort) {\n    nodes {\n      id\n      mediaRecommendation {\n        id\n        title {\n          english\n          native\n          romaji\n        }\n        coverImage {\n          extraLarge\n          large\n          medium\n        }\n      }\n    }\n  }\n  relations {\n    edges {\n      id\n      relationType\n      node {\n        format\n        type\n        id\n        title {\n          english\n          native\n          romaji\n        }\n        coverImage {\n          extraLarge\n          large\n          medium\n        }\n      }\n    }\n  }\n  staff(sort: $staffSort) {\n    nodes {\n      id\n      image {\n        large\n        medium\n      }\n      name {\n        full\n        native\n      }\n    }\n  }\n}"): typeof import('./graphql').MediaCardFragmentDoc;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query MediaDetailQuery($mediaId: Int, $voiceActorLanguage: StaffLanguage, $recommendationSort: [RecommendationSort], $staffSort: [StaffSort]) {\n  Media(id: $mediaId) {\n    ...MediaDetail\n  }\n}"): typeof import('./graphql').MediaDetailQueryDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "fragment PageInfoData on Page {\n  pageInfo {\n    total\n    perPage\n    currentPage\n    lastPage\n    hasNextPage\n  }\n}"): typeof import('./graphql').PageInfoDataFragmentDoc;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "fragment StaffCard on Staff {\n  age\n  description(asHtml: true)\n  gender\n  id\n  primaryOccupations\n  image {\n    large\n    medium\n  }\n  name {\n    full\n    native\n  }\n}\n\nfragment StaffDetail on Staff {\n  age\n  id\n  description(asHtml: true)\n  homeTown\n  siteUrl\n  yearsActive\n  gender\n  primaryOccupations\n  name {\n    full\n    native\n    alternative\n  }\n  image {\n    large\n    medium\n  }\n  dateOfBirth {\n    day\n    month\n    year\n  }\n  dateOfDeath {\n    day\n    month\n    year\n  }\n  characterMedia(sort: $characterMediaSort) {\n    edges {\n      id\n      node {\n        id\n        type\n        coverImage {\n          extraLarge\n          large\n          medium\n        }\n        title {\n          english\n          native\n          romaji\n        }\n      }\n      characters {\n        id\n        name {\n          full\n          native\n        }\n        image {\n          large\n          medium\n        }\n      }\n    }\n  }\n}"): typeof import('./graphql').StaffCardFragmentDoc;


export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}
